site_name: Allen's Knowledge Base
dev_addr: 0.0.0.0:8000
theme: 
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.select
    
plugins:
  - tags
  - meta
  - search
  - awesome-nav
markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
     permalink: "#"
  - callouts