site_name: Allen's Knowledge Base
dev_addr: 0.0.0.0:8000
theme: 
  name: material
  features:
    - content.code.copy
    - content.code.select
plugins:
  - tags
  - meta
  - search
  - literate-nav:
      nav_file: nav.md
markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences